---
orbs:
  python: circleci/python@0.2.1
jobs:
  run_test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Update pip
          command: "pip3 install --upgrade pip"
      - run:
          name: Install Python Dependencies
          command: "pip3 install -r requirements.txt"
      - run:
          name: "Unit Test"
          command: "python -m unittest"
      - store_test_results:
          path: test_reports
      - store_artifacts:
          path: test_reports
version: 2.1
workflows:
  main:
    jobs:
      - run_test
