---
jobs:
  run_test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: "pytest --junitxml=test-reports/junit.xml --html=test_reports/pytest_report.html --self-contained-html"
          name: "Unit Test"
      - store_test_results:
          path: test_reports
      - store_artifacts:
          path: test_reports
version: 2.1
workflows:
  build_test:
    jobs:
      - run_test
